
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#use_frameworks!

# Add new pods below this line
#pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

#pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

#pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

#pod 'Picker', :path => '../node_modules/react-native-picker'

#pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

#pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive'
#pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'

target 'card' do
pod 'NSLogger/NoStrip'
pod 'Fabric'
pod 'Crashlytics'
pod 'Flurry-iOS-SDK/FlurrySDK'
end
