export const Other = {
    redWallet: require('./other/ic_red_wallet.png'),
    announcement_top: require('./other/announcement_top.png'),
    refreshMoney: require('./other/ic_refresh_money.png'),
    transfer: require('./other/ic_transfer.png'),
    caiPiao: require('./other/icon_caipiao.png'),
    mg_holder: require('./other/mg_holder.png'),
    worldCup:{
        SS:require('./worldCup/sanshen.png'),
        bg:require('./worldCup/bg_1.png'),
        IMONE:require('./worldCup/im.png'),
        homeEntrance:require('./worldCup/Bitmap2.png')
    },
    DSF:{
        CP:require('./DSF/CP.png'),
        SS:require('./DSF/SS.png'),
        KY:require('./DSF/kaiyuan.png'),
        IMONE:require('./DSF/IMSport.png'),
        MG:require('./DSF/MG.png'),
        FG:require('./DSF/FG.png'),
        CLOSE_GAME:require('./DSF/kaiyuan_gengduo.png')
    },
    betIco:{
        stdui_arrow_up:require('./../resouce/addon/other/stdui_arrow_up.png'),
        stdui_arrow_down:require('./../resouce/addon/other/stdui_arrow_down.png')
    },
    vip:{
        vipBackGround:require('./vip/VIP_Background.png'),
        vip0:require('./vip/VIP_Icons_V0.png'),
        vip1:require('./vip/VIP_Icons_V1.png'),
        vip2:require('./vip/VIP_Icons_V2.png'),
        vip3:require('./vip/VIP_Icons_V3.png'),
        vip4:require('./vip/VIP_Icons_V4.png'),
        vip5:require('./vip/VIP_Icons_V5.png'),
        vip6:require('./vip/VIP_Icons_V6.png'),
        vip7:require('./vip/VIP_Icons_V7.png'),
        vip8:require('./vip/VIP_Icons_V8.png'),
        vip9:require('./vip/VIP_Icons_V9.png'),
        vip10:require('./vip/VIP_Icons_V10.png'),
        vip11:require('./vip/VIP_Icons_V11.png'),
        vip12:require('./vip/VIP_Icons_V12.png'),
        vip13:require('./vip/VIP_Icons_V13.png'),
        vip14:require('./vip/VIP_Icons_V14.png'),
        vip15:require('./vip/VIP_Icons_V15.png'),
        vip16:require('./vip/VIP_Icons_V16.png'),
        vip17:require('./vip/VIP_Icons_V17.png'),
        vip18:require('./vip/VIP_Icons_V18.png'),
        vip19:require('./vip/VIP_Icons_V19.png'),
        vip20:require('./vip/VIP_Icons_V20.png'),
        // vipV:require('./vip/VIP_Icons_V.png'),
        blueBar:require('./vip/Blue_Bar.png'),
        blueTimeLine:require('./vip/Blue_Timeline.png'),
        greyTimeLine:require('./vip/Grey_Timeline.png'),
        yellowTimeLine:require('./vip/Yellow_Timeline.png'),
        titleBackGround:require('./vip/VIP_TitleBackgroundNew.png'),
    },
    cardGame:{
        homebg:require('./cardGame/home/bg1.png'),
        homeFG:require('./cardGame/home/fg_label.png'),
        homeKY:require('./cardGame/home/ky_label.png'),
        homeMore:require('./cardGame/home/more.png'),
        homeNotice:require('./cardGame/home/notice.png'),
        gameIcoHolder:require('./cardGame/home/default.png'),
        FG:{
            bjl:require('./cardGame/FG/bjl.png'),
            cqznn:require('./cardGame/FG/cqznn.png'),
            csg:require('./cardGame/FG/csg.png'),
            HB:require('./cardGame/FG/HB.png'),
            jgf:require('./cardGame/FG/jgf.png'),
            RC:require('./cardGame/FG/RC.png'),
            rt:require('./cardGame/FG/rt.png'),
            TexasCb:require('./cardGame/FG/TexasCb.png'),
            tz:require('./cardGame/FG/tz.png'),

        },
        KY:{
            0:require('./cardGame/KY/KY_0.png'),
            220:require('./cardGame/KY/KY_220.png'),
            230:require('./cardGame/KY/KY_230.png'),
            380:require('./cardGame/KY/KY_380.png'),
            390:require('./cardGame/KY/KY_390.png'),
            600:require('./cardGame/KY/KY_600.png'),
            610:require('./cardGame/KY/KY_610.png'),
            620:require('./cardGame/KY/KY_620.png'),
            630:require('./cardGame/KY/KY_630.png'),
            720:require('./cardGame/KY/KY_720.png'),
            730:require('./cardGame/KY/KY_730.png'),
            830:require('./cardGame/KY/KY_830.png'),
            860:require('./cardGame/KY/KY_860.png'),
            870:require('./cardGame/KY/KY_870.png'),
            880:require('./cardGame/KY/KY_880.png'),
            900:require('./cardGame/KY/KY_900.png'),
            910:require('./cardGame/KY/KY_910.png'),
            920:require('./cardGame/KY/KY_920.png'),
        }
    }
}
