
export const Images = {
    bbl:{
        gameBg: require('./game/bg.jpg'),
        logo:require('./game/logo.png'),
    }

}


/**
 * 公共图片
 * @type {{topBg: *, topPersonal: *, back: *, topBarArrow: *, topBarList: *, topBarSudoku: *, bottomHomeNormal: *}}
 */
export const common = {
    topBg: require('../resouce/addon/other/top_bg_750.png'),
    topPersonal: require('../resouce/addon/other/index_personal.png'),
    back: require('../resouce/addon/other/top_bar_back.png'),
    topBarList: require('../resouce/addon/other/top_bar_list.png'),
    topBarSudoku: require('../resouce/addon/other/top_bar_sudoku.png'),
    iconNext: require('../resouce/addon/other/icon_next.png'),
    warn: require('../resouce/addon/other/warn.png'),
    close: require('../resouce/addon/other/close.png'),
    noData: require('../resouce/addon/other/no_data.png'),
    noNet: require('../resouce/addon/other/broken_network.png'),
    noPayData: require('../resouce/addon/other/pay_error.png'),
    select: require('../resouce/addon/other/bank_select.png'),
    unSelect: require('../resouce/addon/other/bank_select2.png'),
    downArrow: require('../resouce/addon/agentCenter/arrow.png'),
    backSpace: require('../resouce/addon/other/backspace.png'),
    topBarArrow: require('../resouce/addon/other/top_bar_arrow.png'),
    search: require('../resouce/addon/other/search.png'),
}

//个人中心
export const personal = {
    userDefaultIcon: require('../resouce/addon/userCenterIcon/user_default_icon.png'),
    userDefaultLocalIcon: 'user_default_icon',
    userCenterBg: require('../resouce/addon/userCenterIcon/usercenter_default_background.png'),
    userBarTool: require('../resouce/addon/userCenterIcon/top_bar_tools.png'),
    imgEye: require('../resouce/addon/userCenterIcon/icon_eye.png'),
    imgEye2: require('../resouce/addon/userCenterIcon/icon_eye2.png'),
    iconPay: require('../resouce/addon/userCenterIcon/icon_pay.png'),
    iconDraw: require('../resouce/addon/userCenterIcon/icon_drawings.png'),
    imgNext: common.iconNext,
    iconTransfer: require('../resouce/addon/userCenterIcon/icon_transfer.png'),
    daiKaiJjiangIcon: require('../resouce/addon/userCenterIcon/dai.png'),
    jiangliIcon: require('../resouce/addon/userCenterIcon/jiangli.png'),
    yiKaiJiangIcon: require('../resouce/addon/userCenterIcon/dingdan.png'),
    personalInfo: require('../resouce/addon/userCenterIcon/personal_info.png'),
    secure: require('../resouce/addon/userCenterIcon/secure.png'),
    account: require('../resouce/addon/userCenterIcon/account.png'),
    agent: require('../resouce/addon/agentCenter/group.png'),
    message: require('../resouce/addon/userCenterIcon/person_news.png'),
    collect: require('../resouce/addon/userCenterIcon/shoucang.png'),
    imgSet: require('../resouce/addon/userCenterIcon/set.png'),
    toolUpdate: require('../resouce/addon/userCenterIcon/tool_update.png'),
    toolAbout: require('../resouce/addon/userCenterIcon/tool_about.png'),
    toolFeedBack: require('../resouce/addon/userCenterIcon/feedback.png'),
    toolMusic: require('../resouce/addon/userCenterIcon/tool_music.png'),
    toolPassword: require('../resouce/addon/userCenterIcon/tools_password.png'),
    toolPassword2: require('../resouce/addon/userCenterIcon/tools_password2.png'),
    bankManager: require('../resouce/addon/userCenterIcon/bank_manage.png'),
    payRecord: require('../resouce/addon/userCenterIcon/pay_records.png'),
    withDraw: require('../resouce/addon/userCenterIcon/withdraw_withdraw.png'),
    username: require('../resouce/addon/userCenterIcon/user.png'),
    password: require('../resouce/addon/userCenterIcon/password.png'),
    affCode: require('../resouce/addon/userCenterIcon/affcode.png'),
    check: require('../resouce/addon/userCenterIcon/icon_checked.png'),
    unCheck: require('../resouce/addon/userCenterIcon/icon_uncheck.png'),
    signIn: require('../resouce/addon/userCenterIcon/signIn.png'),
    email: require('../resouce/addon/userRegister/email.png'),
    identityNumber: require('../resouce/addon/userRegister/identity_number.png'),
    phoneNumber: require('../resouce/addon/userRegister/phone_number.png'),
    QQ: require('../resouce/addon/userRegister/qq.png'),
    validateCode: require('../resouce/addon/userRegister/validate_code.png'),
    tzRecord: require('../resouce/addon/userCenterIcon/tz_record.png'),
    ctRecord: require('../resouce/addon/userCenterIcon/ct_record.png'),
    userSheet: require('../resouce/addon/userCenterIcon/user_sheet.png'),
    userManager: require('../resouce/addon/userCenterIcon/user_manager.png'),
    agentCommission: require('../resouce/addon/userCenterIcon/agent_commission.png'),
    teamSheet: require('../resouce/addon/userCenterIcon/team_sheet.png'),
    onlineServicer: require('../resouce/addon/userCenterIcon/service.png'),
    more: require('../resouce/addon/userCenterIcon/agent_more.png'),
    shareFriends: require('../resouce/addon/userCenterIcon/invite_friends.png'),
    promotions: require('../resouce/addon/userCenterIcon/promotions.png'),
}


//用户充值
//用户充值
export const userPay = {
    noPayData: common.noPayData,
    qqPay: require('../resouce/addon/other/qq_pay.png'),
    thirdPay: require('../resouce/addon/other/third_pay.png'),
    wechat: require('../resouce/addon/other/wechat.png'),
    alipay: require('../resouce/addon/other/alipay.png'),
    bank: require('../resouce/addon/other/bank.png'),
    jdzf: require('../resouce/addon/other/jdzf.png'),
    userAlipayHelp01: require('../resouce/addon/other/alipay01.png'),
    userAlipayHelp02: require('../resouce/addon/other/alipay02.png'),
    userWechatPayHelper02: require('../resouce/addon/other/wechat02.png'),
    userAlipayHelp03: require('../resouce/addon/other/alipay03.png'),
    userWechatPayHelper03: require('../resouce/addon/other/wechat03.png'),
    userAlipayHelp04: require('../resouce/addon/other/alipay04.png'),
    userWechatPayHelper04: require('../resouce/addon/other/wechat04.png'),
    paidui01: common.select,
    paidui02: require('../resouce/addon/other/paidui22.png'),
    paidui03: require('../resouce/addon/other/win.png'),
    step1: require('./pay_step/step_1.png'),
    step3: require('./pay_step/step_3.png'),
    step4: require('./pay_step/step_4.png'),
    step5: require('./pay_step/step_5.png'),
    step6: require('./pay_step/step_6.png'),
    step7: require('./pay_step/step_7.png'),
    step8: require('./pay_step/step_8.png'),
    step9: require('./pay_step/step_9.png'),
    stepWx1: require('../asset/pay_step/wx_public/step1.png'),
    stepWx2: require('../asset/pay_step/wx_public/step2.png'),
    stepWx3: require('./pay_step/wx_step_3.png'),
    stepWx4: require('./pay_step/wx_step_4.png'),
    payTypeWx: require('./pay_icon/wx.png'),
    payTypeAlipay: require('./pay_icon/alipay.png'),
    payTypeJdzf: require('./pay_icon/jdzf.png'),
    payTypeUnionpay: require('./pay_icon/wy.png'),
    payTypeOther: require('./pay_icon/unionpay.png'),
    payTypeBank: require('./pay_icon/bank.png'),

}

//账变明细
export const userAccount = {
    calendar: require('../resouce/addon/userAccount/calendar.png'),
    calendarDropDown: require('../resouce/addon/userAccount/calendar_drop_down.png'),
    dayAfter: require('../resouce/addon/userAccount/day_after.png'),
    dayBefore: require('../resouce/addon/userAccount/day_before.png')
}
//投注页面
export const betIcon = {
    bgPlace: require('../resouce/addon/other/bg_place.png'),
    bgPlace02: require('../resouce/addon/other/bg_place02.png'),
    back: require('../resouce/addon/other/fanhui2.png'),
    handPointing: require('../resouce/addon/other/hand_pointing.png'),
    topBg: require('../resouce/addon/other/top_bg.png'),
    shake: require('../resouce/addon/other/icon_shake.png'),
    explain: require('../resouce/addon/other/explain.png'),
    check: personal.check,
    unCheck: personal.unCheck,
    orderTop: require('../resouce/addon/other/order_top.png'),
    orderBottom: require('../resouce/addon/other/order_bottom.png'),
    orderQingChu: require('../resouce/addon/other/icon_qingchu.png'),
    success: common.select,
    redCheck: require('../resouce/addon/other/red_check.png')
}

//账号信息
export const gameUI = {
    //useraccout
    btnPhone: require('./game/account/btn_phone.png'),
    btnRelName: require('./game/account/btnRelName.png'),
    btnRelChangeBg: require('./game/account/btnRelChangeBg.png'),
    persionText:require('./game/account/persionText.png'),
    personBg:require('./game/account/personBg.png'),
    btnClose:require('./game/account/btnClose.png'),
    btnOk:require('./game/account/btn_queren.png'),
    pwdOpen:require('./game/account/pwdOpen.png'),
    pwdClose:require('./game/account/pwdClose.png'),
    bindPhoneBg:require('./game/account/bindPhoneBg.png'),
    titlePhone:require('./game/account/titlePhone.png'),
    //guest
    guestBg:require('./game/guest/gusetBg.png'),
    //moneyOut
    titleMoneyOut:require('./game/moneyOut/titleMoneyOut.png'),
    iconMoneyOut:require('./game/moneyOut/iconMoneyOut.png'),
    btnOut:require('./game/moneyOut/btn_out.png'),
    payOutTypeBank:require('./game/moneyOut/payOutTypeBank.png'),
    payOutTypeZFB:require('./game/moneyOut/payOutTypeZFB.png'),
    payOutTypeZFB_notSupport:require('./game/moneyOut/img_tx_zfb02.png'),
    payTypeSelectBg:require('./game/moneyOut/payTypeSelectBg.png'),
    payOutBg:require('./game/moneyOut/payOutBg.png'),
    payOutTopIcon:require('./game/moneyOut/payOutTopIcon.png'),
    payOutMoneyLabel:require('./game/moneyOut/moneyLabel.png'),
    question:require('./game/moneyOut/quesion.png'),
    inputMoneyBg:require('./game/moneyOut/inputMoneyBg.png'),
    bankBtn:require('./game/moneyOut/bankbtn.png'),
    zfbBtn:require('./game/moneyOut/zfbbtn.png'),
    query:require('./game/moneyOut/query.png'),
    bangNumBg:require('./game/moneyOut/img_tx_bangBg.png'),
    //moneyPay
    moneyInBg:require('./game/moneyPay/moneyInBg.png'),
    moneyBottomBg:require('./game/moneyPay/moneyBottomBg.png'),
    btn_onLine:require('./game/moneyPay/btn_guset_online.png'),
    title_pay:require('./game/moneyPay/title_payType.png'),
    title_qr:require('./game/moneyPay/title_qrCode.png'),
    btn_minxi:require('./game/moneyPay/btn_minxi.png'),
    payTopLeftBg:require('./game/moneyPay/pay_top_left_bg.png'),
    payBack:require('./game/moneyPay/pay_back.png'),
    payBackBg:require('./game/moneyPay/pay_back_bg.png'),
    payTopIcon:require('./game/moneyPay/pay_top_icon.png'),
    payTopTxt:require('./game/moneyPay/pay_top_txt.png'),
    //payType
    payTypeBg:require('./game/moneyPay/pay_type_bg.png'),
    payTypeWx:require('./game/moneyPay/type/pay_type_wx.png'),
    payTypeWxFix:require('./game/moneyPay/type/pay_type_wx_fix.png'),
    payTypeWxGZH:require('./game/moneyPay/type/pay_type_wxgzh.png'),
    payTypeQQ:require('./game/moneyPay/type/pay_type_qq.png'),
    payTypeQQFix:require('./game/moneyPay/type/pay_type_qq_fix.png'),
    payTypeZFB:require('./game/moneyPay/type/pay_type_zfb.png'),
    payTypeZFBFix:require('./game/moneyPay/type/pay_type_zfb_fix.png'),
    payTypeYL:require('./game/moneyPay/type/pay_type_yl.png'),
    payTypeWy:require('./game/moneyPay/type/pay_type_wy.png'),
    payTypeYhzz:require('./game/moneyPay/type/pay_type_yhzz.png'),
    payTypeJD:require('./game/moneyPay/type/pay_type_jd.png'),
    payTypeVIP:require('./game/moneyPay/type/pay_type_vip.png'),

    btnPayNormal:require('./game/moneyPay/btnPayNormal.png'),
    btnPayHight:require('./game/moneyPay/btnPayHight.png'),
    btnPayVIPNormal:require('./game/moneyPay/btnPayVIPNormal.png'),
    btnMoneyHight:require('./game/moneyPay/btnMoneyHight.png'),
    btnMoneyBg:require('./game/moneyPay/btnMoneyBg.png'),
    //btn
    typeJD:require('./game/moneyPay/type/typeJD.png'),
    typeQQ:require('./game/moneyPay/type/typeQQ.png'),
    typeWX:require('./game/moneyPay/type/typeWX.png'),
    typeWX_GZ:require('./game/moneyPay/type/typeWX_GZ.png'),
    typeZFB:require('./game/moneyPay/type/typeZFB.png'),
    typeBank:require('./game/moneyPay/type/typeYN.png'),
    typeWy:require('./game/moneyPay/type/typeWy.png'),
    typeTrans:require('./game/moneyPay/type/typeTrans.png'),

    //stepOnebg1
    stepOneBg1:require('./game/moneyPay/stepOnebg1.png'),
    stepOneBg2:require('./game/moneyPay/stepOnebg2.png'),

    listItemBg:require('./game/moneyPay/listItemBg.png'),
    listItemVIPBg:require('./game/moneyPay/listItemVIPBg.png'),
    fixedListItemBg:require('./game/moneyPay/pay_type_fixed_bg.png'),
    fixedListItemBg1:require('./game/moneyPay/pay_type_fixed_bg1.png'),
    moneyLabelBg:require('./game/moneyPay/money_label_bg.png'),
    payExpand:require('./game/moneyPay/pay_expand.png'),
    payCollapse:require('./game/moneyPay/pay_collapse.png'),
    downArrow:require('./game/moneyPay/down_arrow.png'),
    //alet
    uiTitleBg:require('./game/uiTitleBg.png'),
    uiTitleBg1:require('./game/uiTitleBg1.png'),
    title_fix:require('./game/title_fix.png'),
    btn_fanhui:require('./game/btn_fanhui.png'),
    closeIcon:require('./game/close.png'),
    czmxIcon:require('./game/czmx_icon.png'),
    txmxIcon:require('./game/txmx_icon.png'),
    czmxTip:require('./game/czmx_tip.png'),
    txmxTip:require('./game/txmx_tip.png'),
    onlineService:require('./game/online_service.png'),
    czmxAll:require('./game/czmx_qb.png'),
    czmxAll_Normal:require('./game/czmx_qb_normal.png'),
    czmxFail:require('./game/czmx_sb.png'),
    czmxFail_Normal:require('./game/czmx_sb_normal.png'),
    czmxDone:require('./game/czmx_ywc.png'),
    czmxDone_Normal:require('./game/czmx_ywc_normal.png'),
    img_czmx_dkMenu:require('./game/img_czmx_dkMenu.png'),
}

export const gameShare = {
    //useraccout
    boxBg: require('./game/share/boxBg.png'),
    btnAndroid:require('./game/share/btnAndroid.png'),
    btnApple:require('./game/share/btnApple.png'),
    btnWX:require('./game/share/btnWX.png'),
    btPYQ:require('./game/share/btPYQ.png'),
    fengxiangBg:require('./game/share/fengxiangBg.png'),
    imgMM:require('./game/share/img_mm.png'),
    imgBox:require('./game/share/imgBox.png'),
    btn_wxShare:require('./game/share/btn_wxShare.png'),
    btn_Copy:require('./game/share/btnCopy.png'),
}
